# See: https://taskfile.dev/api/

version: "3"

tasks:
  migrate:
    aliases:
      - mig
    desc: "Generate migrations"
    cmds:
      - go run ./cmd/migrator/ --storage-path=./storage/auth_service.db --migrations-path=./migrations

  test_migrate:
    aliases:
      - tmig
    desc: "Generate test migrations"
    cmds:
      - go run ./cmd/migrator/ --storage-path=./storage/auth_service.db --migrations-path=./tests/migrations --migrations-table=migrations_test

  run:
    aliases:
      - r
    desc: "run auth-service"
    cmds:
     - go run cmd/auth_service/main.go --config=./config/local.yaml