# See: https://taskfile.dev/api/

version: "3"

tasks:
  migrate:
    aliases:
      - mig
    desc: "Generate migrations"
    cmds:
      - go run ./cmd/migrator/ --storage-path=./storage/auth_service.db --migrations-path=./migrations